### ISSUE TITLE
This package is not optimal for loading within an ESM context

### ISSUE THREAD

**Issue by n1ru4l** [Codex-/cosmiconfig-typescript-loader#36]
hey there, I am a maintainer of `graphql-config` and `graphql-code-generator` and we are relying on this package. Codegen and `graphql-config` support both ESM and CommonJS.

It is totally fine that your package only supports CommonJS, however, it currently causes confusing behavior which requires us to use hacks for making it work on both CommonJS and ESM.

See the original issue that reported this "bug": https://github.com/dotansimha/graphql-code-generator/issues/8212

There is even a library published to npm for resolving this issue: https://www.npmjs.com/package/default-import

See: https://github.com/kamilkisiela/graphql-config/blob/318c9fd48867364f804731126448b2ff49ea07c9/src/helpers/cosmiconfig.ts#L6-L7

```ts
import unsecure_loadTs from 'cosmiconfig-typescript-loader';

/** The underlying module gives us { default: loadTs } on ESM but no default on CJS :) */
const loadTs: typeof unsecure_loadTs = (unsecure_loadTs as any)?.default ?? unsecure_loadTs;
```

Today, the probably simplest solution for addressing this problem within THIS library, and not shifting it to the library consumers are avoiding default exports.

This would require replacing the existing default export with a named export. Of course, this is a breaking change.
I created https://github.com/Codex-/cosmiconfig-typescript-loader/pull/37 for showcasing this.

**Comment by Codex-** [comment]
Yeah, the default export was to primarily ease the transition between the original unmaintained package and this one. Happy to change this to use named exports, as you've outlined, it's just better here.

Since this changes the public API, I'll have to major version bump this after merging the PR

**Comment by n1ru4l** [comment]
@Codex- This PR should fix it by switching to named exports: https://github.com/Codex-/cosmiconfig-typescript-loader/pull/37

**Comment by n1ru4l** [comment]
@Codex- Note that the README examples are still invalid (for ESM).

You cannot do `import { TypeScriptLoader } from "cosmiconfig-typescript-loader";` for an CJS module.

You need to do:

```ts
import mod from "cosmiconfig-typescript-loader";
const { TypeScriptLoader } = mod;
```

**Comment by Codex-** [comment]
Fixed with #37 

Released under 4.0.0

**Comment by Codex-** [comment]
> @Codex- Note that the README examples are still invalid (for ESM).
> 
> You cannot do `import { TypeScriptLoader } from "cosmiconfig-typescript-loader";` for an CJS-only module in ESM.
> 
> You need to do:
> 
> ```ts
> import mod from "cosmiconfig-typescript-loader";
> const { TypeScriptLoader } = mod;
> ```

This should work, did with my testing at least:

`smoke-test-esm.mjs`:
```js
import { TypeScriptLoader } from "../dist/cjs/index.js";
TypeScriptLoader();

console.info("Loaded with ESM successfully");
```

```
> node ./smoke-test-esm.mjs 
Loaded with ESM successfully
```

**Comment by n1ru4l** [comment]
@Codex- You are right! ESM is so confusing...

**Comment by Codex-** [comment]
Hah, it can be punishing at time. 

In `graphql-config` you can change your import to `import { TypeScriptLoader as loadTs } from 'cosmiconfig-typescript-loader';` and just bump the package version 👌

**Comment by n1ru4l** [comment]
https://github.com/kamilkisiela/graphql-config/pull/1126 :)
