### ISSUE TITLE
bug: fails to load config in ESM project

### ISSUE THREAD

**Issue by elijaholmos** [Codex-/cosmiconfig-typescript-loader#60]
In any project where `"type": "module"` exists in the `package.json`, this package crashes when trying to load a config file. The error that appears is similar to:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\coding-work\cosmiconfig\cosmiconfigts-repro\amazing.config.ts
require() of ES modules is not supported.
require() of C:\coding-work\cosmiconfig\cosmiconfigts-repro\amazing.config.ts from C:\coding-work\cosmiconfig\cosmiconfigts-repro\node_modules\.pnpm\cosmiconfig-typescript-loader@4.2.0_whq6te2zcgakt4fgsicma7l33e\node_modules\cosmiconfig-typescript-loader\dist\cjs\index.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from C:\coding-work\cosmiconfig\cosmiconfigts-repro\package.json.
```

The cause of the issue appears to be with the `require` statement here:
https://github.com/Codex-/cosmiconfig-typescript-loader/blob/37a30047620e9fe5826d37ca78e67a958ed8341d/lib/loader.ts#L12-L14

I can provide a sample repro repo if requested.

related issue: https://github.com/dotansimha/graphql-code-generator-community/issues/225

**Comment by Codex-** [comment]
I'm very keen to support `import` and remove the `cjs` limitation, however this requires that `cosmiconfig` supports `esm` too. Currently they only emit `cjs`: https://github.com/davidtheclark/cosmiconfig/blob/main/package.json#L95

**Comment by geisterfurz007** [comment]
For visibility, this is the related upstream PR https://github.com/davidtheclark/cosmiconfig/pull/283

**Comment by tal-rofe** [comment]
Is there any workaround?

**Comment by Codex-** [comment]
> Is there any workaround?

For not being able to load esm? Can't do much about this until cosmiconfig supports this upstream

**Comment by tianyingchun** [comment]
i just create temp module `@armit/config-loader` to support `esm`,`cjs`, type:module

**Comment by elijaholmos** [comment]
with [cosmiconfig 8.2.0](https://github.com/cosmiconfig/cosmiconfig/blob/HEAD/CHANGELOG.md#820), ESM is now supported! 🎉

**Comment by tianyingchun** [comment]
it seems that their is a bug.
```ts
const loadJs: LoaderAsync = async function loadJs(filepath) {
  try {
    const { href } = pathToFileURL(filepath);
    return (await import(href)).default;
  } catch (error) {
    return loadJsSync(filepath, null);
  }
};
```
 return (await import(href)).default; always return `undefined` for project 

`type:module`

**Comment by tianyingchun** [comment]
consider below example
```valid.config.js

```ts
import { defineConfig } from 'vite';

// it is `esm` module causeof type:`module`
export const test = defineConfig({
  cake: 'a lie',
});

```

it will aways return me undefined.

**Comment by Codex-** [comment]
With esm now supported I'll have to make some changes to support this, PRs welcome but I'll try look at it this week

**Comment by Codex-** [comment]
This is now in progress, draft PR here https://github.com/Codex-/cosmiconfig-typescript-loader/pull/96

**Comment by Codex-** [comment]
Progress can be tracked in #97
