### ISSUE TITLE
Why this package declaring @types/node as peer dependency?

### ISSUE THREAD

**Issue by thekip** [Codex-/cosmiconfig-typescript-loader#78]
It shouldn't be there, as it brings no value. This package (when consumed) has no references to `@types/node` and should not include it as a peer.

**Comment by Codex-** [comment]
This currently depends on `ts-node` which specifies `@types/node` as a peer:
https://github.com/TypeStrong/ts-node/blob/main/package.json#L146

**Comment by thekip** [comment]
Missed that one. Thanks
