### ISSUE TITLE
Consider using jiti for typescript loading instead of ts-node

### ISSUE THREAD

**Issue by thekip** [Codex-/cosmiconfig-typescript-loader#85]
FYI
https://github.com/lingui/js-lingui/pull/1474

**Comment by Codex-** [comment]
Thanks, I'll have a look into it.

The problem I had with using the tsc API directly was that it transformed without enforcing the type system when used how they recommended lol.

I was also following the progress of both `@swc` for enforcing types, and [`stc`](https://github.com/dudykr/stc) too.

**Comment by thekip** [comment]
The main point of switching from ts-node (or at least changing the way it works) is not in the type system. 

The current trend of ecosystem is transpiling should be done separately from type checking, because the second is very slow. 

For the use cases which cosmiconfig trying to tackle, i don't think type checking ever needed. 

The main problem with current implementation is that ts-node registered process-wide. That causes the following issues:
 
- if in the host application / library happened to call to TypescriptLoader more than once ts-node get registered more than one time too. It causes one, two, ten, and more compilation of the files (not only a config, read following!).
- When ts-node get registered it affects all following require calls, not only requires from config:
  ```
   - load cli util (host)
   - load config using TypescriptLoader
      -- (ts-node get registered)
      -- load imports tree from config (go through ts-node)
   - continue loading cli util (go through ts-node) <--- shouldn't be, because it take time!
  ```

Jest for example, [solve second problem](https://github.com/facebook/jest/blob/main/packages/jest-config/src/readConfigFileAndSetRootDir.ts#L81-L98) by (pseudocode): 
```ts
"ts-node".register()
loadConfig("jest.config.ts")
"ts-node".register(false)
```

But this works on assumptions. They assume config would not have function which would be called after config initialization.

Example: 
```ts
// my.config.ts
module.exports = {
  [...]
  someFn: async () => {
      const file = await import("./another-file.ts")
  }
}
```
Then if we do as Jest:
```ts
"ts-node".register()
const config = loadConfig("my.config.ts")
"ts-node".register(false)

// ------

await config.someFn() // <!-- Error here, ts-node already disabled at this point, so import another `ts` file would fail.
```

So Jest-way is not suitable for all projects.

Jiti unlike ts-node was created for such cases and should transpile only one branch of requires. 

  ```
   - load cli util (host)
   - load config using Jiti
      -- Separate VM created
      -- load imports tree from config in separate VM <- go through Jiti
   - continue loading cli util <- not affected by Jiti
  ```

**Comment by olawalejuwonm** [comment]
Does jiti transpile-only?

**Comment by Codex-** [comment]
@olawalejuwonm the types should be enforced, https://github.com/Codex-/cosmiconfig-typescript-loader/blob/ae3be22506f19eaf051f12b48ae2f01ae38ac739/lib/loader.spec.ts#L38

**Comment by olawalejuwonm** [comment]
I don't want it to type check @Codex-

**Comment by Codex-** [comment]
@olawalejuwonm why would you use the typescript loader if you don't want to use types? If there is an actual problem with using the ts loader as intended please open an issue with reproduction steps.
