### ISSUE TITLE
ESM Support

### ISSUE THREAD

**Issue by Codex-** [Codex-/cosmiconfig-typescript-loader#97]
Historically cosmiconfig did not support ESM, however this was recently introduced with [8.2.0](https://github.com/cosmiconfig/cosmiconfig/blob/HEAD/CHANGELOG.md#820)

Tasks
- [x] Update build to emit both esm and cjs
- [x] Update config source loading to target `require` or `import`
- [x] Test package exports compliance
- [x] Update Jest test suite
- [x] Update smoke tests
- [x] Perform manual testing

Pull Request: https://github.com/Codex-/cosmiconfig-typescript-loader/pull/96

**Comment by Rigo-m** [comment]
Is it possible to test the new PR in an edge channel release?
Having problems using cosmiconfig in a esm-only module environment, I understand that this upgrade is delicate since this library is so used, but was wondering if we could try esm support at our own risk somehow :)

**Comment by Codex-** [comment]
@Rigo-m I'll post in here and tag you when it's in re-release :)

**Comment by Rigo-m** [comment]
Thank you Alex! 🙂

**Comment by Codex-** [comment]
@Rigo-m if you get a chance, the branch is ready for testing

**Comment by Rigo-m** [comment]
Hi @Codex-, sorry for the late response. Unfortunately I switched to c12 as it already implemented jiti/esm support and typescript loading out of the box, hence I didn't have a reproduction ready to test it. Although I took a look at the code and it LGTM :) Wish you a happy day

**Comment by Codex-** [comment]
@Rigo-m no problem! Thanks anyway :)
